# Permalinks
# permalink:        pretty
# permalink: /blog/:categories/:year/:month/:day/:title/
permalink: /:year/:month/:title.html
# Setup
title:            Adson Batista
tagline:          'Minhas notas'
description:      '<img src="https://adsonbatista.github.io/images/public/hello.png"> A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://adsonbatista.github.io

author:
  name:           'Adson Batista'
  # url:            https://twitter.com/mdo

pagination:
  enabled: true
  per_page: 5
  permalink: '/blog//page/:num/'
  title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

gems:
  - jekyll-paginate-v2
# Custom vars
version:          2.0.0

github:
  repo:           # https://github.com/poole/lanyon
