# Permalinks
permalink:        pretty

# Setup
title:            Adson Batista
tagline:          'Minhas notas'
description:      '<img src="https://adsonbatista.github.io/images/public/hello.jpg"> A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://adsonbatista.github.io

author:
  name:           'Adson Batista'
  # url:            https://twitter.com/mdo

paginate:         5
gems: ["jekyll-paginate"]
# Custom vars
version:          2.0.0

github:
  repo:           # https://github.com/poole/lanyon
